FROM python:3.10-slim
WORKDIR /usr/src/api
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8080
CMD ["bash", "-c", "exec gunicorn -b 0.0.0.0:$PORT predict_api:app"]