FROM python:3.12-bookworm
WORKDIR /usr/src/ui
RUN pip install --upgrade pip setuptools wheel
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5000
CMD ["python3", "ui_server.py"]